
---
on:
    pull_request:
        branches:
        - develop
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Setup dotnet
          uses: actions/setup-dotnet@v5
          with:
            dotnet-version: | 
              9.0.x
        - uses: actions/checkout@v5
        - name: restore
          run: dotnet restore src/Presentation/Nop.Web/Nop.Web.csproj
        - name: build
          run: dotnet build --configuration Debug src/Presentation/Nop.Web/Nop.Web.csproj
        - name: test (generate trx report)
          run: |
           mkdir -p test-results/trx
           dotnet test src/Tests/Nop.Tests/Nop.Tests.csproj \
           --logger "trx;LogFilePrefix=testResults" \
           --results-directory test-results/trx

        - name: Install ReportGenerator
          run: dotnet tool install -g dotnet-reportgenerator-globaltool
        - name: Generate HTML test report
          run: |
           mkdir -p test-results/html
           reportgenerator \
            -reports:test-results/trx/*.trx \
            -targetdir:test-results/html

        - name: Install trx2junit
          run: pip install trx2junit
         
        - name: Convert TRX to JUnit
          run: |
            mkdir -p test-results/junit
            trx2junit test-results/trx/*.trx
            mv *.xml test-results/junit/

 
        - name: publish
          run: dotnet publish --configuration Release src/Presentation/Nop.Web/Nop.Web.csproj --output published
